site:
  label: 网站设置
  items:
    sub_title:
      name: 副标题
      label: 副标题
      type: text
    archives_title:
      name: archives_title
      label: 归档页标题
      type: text
      default: '博客'
      description: '/archives 页面显示的标题名字'
    photos_title:
      name: photos_title
      label: 图库页标题
      type: text
      default: '图库'
      description: '/photos 页面显示的标题名字'
    journals_title:
      name: journals_title
      label: 日志页标题
      type: text
      default: '日志'
      description: '/journals 页面显示的标题名字'
sns:
  label: 社交资料
  items:
    github:
      name: github
      label: github
      type: text
    weibo:
      name: weibo
      label: 微博
      type: text
    wechat:
      name: wechat
      label: 微信二维码
      type: text
    qq:
      name: qq
      label: QQ二维码
      type: text
    bilibili:
      name: bilibili
      label: bilibili
      type: text
    email:
      name: email
      label: 邮箱
      type: text
    rss:
      name: rss
      label: rss
      type: rss